name: grincess-actions
on:
  issues:
    types: [opened]
jobs:
  issues-labels:
    runs-on: windows-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "syntax"
